apiVersion: v1
kind: Service
metadata:
  name: dataforge-api-service
  namespace: dataforge-api
spec:
  selector:
    app: dataforge-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort # Para acceder a la API desde fuera del cl√∫ster de Minikube
