apiVersion: v1
kind: Service
metadata:
  name: dataforge-db-service
  namespace: dataforge-api
spec:
  selector:
    app: dataforge-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
