apiVersion: v1
kind: Secret
metadata:
  name: dataforge-db-secret
  namespace: dataforge-api
type: Opaque
data:
  # Replace 'mysecretpassword' with your actual password encoded in Base64
  # Example: echo -n 'mysecretpassword' | base64
  postgres-password: bXlzZWNyZXRwYXNzd29yZA==
